### ISSUE TITLE
Can't start openbox session

### ISSUE THREAD

**Issue by kulik512** [Witko/nvidia-xrun#100]
Hi folks, hi Witko.

I installed the nvidia-xrun step by step in accordance with the archwiki but I cannot startup openbox session. After starting "nvidia-xrun" (in Ctrl+Alt+F2), I get an error https://pastebin.com/raw/YpDys5NV (it's from ~/.local/share/xorg/Xorg.1.log)
According to the error log problem in:
```bash
[ 117.658] (EE) Screen 0 deleted because of no matching config section.
[ 117.658] (II) UnloadModule: "modesetting"
[ 117.658] (EE) Device(s) detected, but none match those in the config file.
```
This's errors look like what I have a problem with my first monitor. What could be the reasons for this?
Details: Manjaro + KDE (two monitors)

**Comment by WhyNotHugo** [comment]
@kulik512 I'm having the same error. How did you fix it?

**Comment by kulik512** [comment]
@WhyNotHugo I was easy :)
Installed Windows

**Comment by WhyNotHugo** [comment]
Oh, the solution was a lot simpler than that, figured it out and documented it here, in case anybody cares: https://github.com/Witko/nvidia-xrun/issues/89#issuecomment-495946663

**Comment by kulik512** [comment]
@WhyNotHugo Its was cool investigation from your side. 
But I still think that nvidia-xrun sucks. Would be better using dual-boot with Windows for games.
