### ISSUE TITLE
Add the possibility to disable device removal

### ISSUE THREAD

**Issue by michelesr** [Witko/nvidia-xrun#112]
From https://github.com/michelesr/nvidia-xrun-pm/issues/5

@guydunigo would like a way to disable the device removal in the script. I think this can be implemented as a flag in the config file (like `REMOVE_DEVICE`) that can be defaulted to `1` and manually set to `0` by the users that don't want nvidia-xrun to remove the device after unloading the nvidia modules.

**Comment by michelesr** [comment]
Another alternative is to create an option `ENABLE_PM` that tells nvidia-xrun that if set to `0` disables all the `rescan`/`add`/`remove` and PM operations so the user is free to handle the device the preferred way (either manually or with the help of powertop/TLP).

**Comment by michelesr** [comment]
@guydunigo can you please see if this `REMOVE_DEVICE=0` works for you? In my machine doesn't work due to the power state bug that affects new graphic cards... if I don't remove the device and initialize it again via rescan I get this when trying to bring the card on again:

```pci 0000:01:00.0: Refused to change power state, currently in D3```

**Comment by guydunigo** [comment]
@michelesr Yes, it works. The card goes well into sleep and back on again.
