### ISSUE TITLE
remove pci bus from kernel.

### ISSUE THREAD

**Issue by ingmarcosp** [Witko/nvidia-xrun#119]
I'm Using opensuse leap 15.1 and the last release remove, literally from kernel the discrete graphics card, and don't show up again. When I do the 
`
sudo lspci | egrep "VGA|3D" `

ony show up the intel graphics.

**Comment by michelesr** [comment]
That's the default behavior. If CONTROLLER_BUS_ID and DEVICE_BUS_ID are set
correctly the nvidia-xrun should be able to add the card back again the
next time it's executed. You can set REMOVE_DEVICE=0 to disable this
behavior.

You can tweak those options in /etc/default/nvidia-xrun.

**Comment by ingmarcosp** [comment]
ok, thanks!
