### ISSUE TITLE
Mouse click does not work.

### ISSUE THREAD

**Issue by NeuroSerpens** [Witko/nvidia-xrun#13]
I obviously just can't play anything if I can't click.

**Comment by andreas-center** [comment]
How do you start your games? Try starting it with openbox.  `nvidia-xrun openbox-session`

Here is a similar issue: https://github.com/Witko/nvidia-xrun/issues/6

**Comment by NeuroSerpens** [comment]
I have tried to xrun xterm, xrun steam, xrun the game directly, xrun xmonad, everything... If this only works with one window manager I'd rather just keep using primusrun.

**Comment by andreas-center** [comment]
@NeuroSerpens Well, i dont know if it works with other window managers. Never tried another one. I got the advice to use openbox and it worked. If you care about more FPS then nvidia-xrun is way better (gave me ~30FPS more than primusrun). Try openbox and check if it works. Maybe @Witko can help you out.

**Comment by NeuroSerpens** [comment]
I guess it doesn't hurt to try. It works in openbox, but now everything is stuck in 1024x768 instead of 1366x768...
I saw someone comment this on another issue but I didn't understand how he added a new mode with xrandr...

**Comment by NeuroSerpens** [comment]
I managed to add the new mode but it just seems everything was shifted 342 pixels to the left because I couldn't access the right portion of the screen and now I can't access the left... Playing for hours with less fps would have been better than this....................................................................................

**Comment by Witko** [comment]
Dear NeuroSerpens,
nobody is forcing you to use nvidia-xrun. For me the difference was extreme. If you have nvidia card with performance of integrated then dont even bother with this.

As for the issues - nvidia-xrun does NOT initialize X server in any way other than setting the nvidia card and currently does not aim to do so. Its quite same as if you would run xinit yourself. Terefore we currently rely on openbox to do so to make our lives easier..
Im not sure why your window manager is not working - i can try to help - but first create an issue for this.
