### ISSUE TITLE
Missing audio when HDMI is connected

### ISSUE THREAD

**Issue by Mte90** [Witko/nvidia-xrun#143]
Right now the audio is not shared when I am using HDMI, the television show the video with no problems but no audio.
Maybe is something that can achieved with the xorg settings?

**Comment by michelesr** [comment]
That looks like a pulseaudio setting more than a xorg setting. Have you tried messing around with `pavucontrol` to set the right output audio interface?

**Comment by Mte90** [comment]
I tried, KDE in other tty doesn't have this problem.
I want to try again today just to see if the last time I tried I did all the tests.
I think that is something that I have to do any time I start the new tty, so I was thinking if it was possible to do a script that check if the cable is connected and on nvidia-xrun add that support.

**Comment by Mte90** [comment]
Checked with pavucontrol I could change and the audio works.
