### ISSUE TITLE
Black / blank screen.

### ISSUE THREAD

**Issue by NeuroSerpens** [Witko/nvidia-xrun#17]
Since Arch's last update it doesn't matter what I run with nvidia-xrun, I just get a black screen.

**Comment by NeuroSerpens** [comment]
Nevermind. Fixed it.

**Comment by ethragur** [comment]
Can you please tell us how to fix it? Have the same problem here since the nvidia update

**Comment by ethragur** [comment]
I fixed it by uninstalling bumblebee
