### ISSUE TITLE
fatal error: Cannot establish any listening sockets

### ISSUE THREAD

**Issue by perbasilopou** [Witko/nvidia-xrun#19]
Hi!!
Thank you for creating this for all the linux users.
I installed nvidia-xrun from AUR with no errors or something.
I may be doing something wrong but i get this error when I switch to tty2 and run 

nvidia-xrun steam

I freshly installed Manjaro 16.06 pre3 KDE with bumblebee and the proprietary drivers that mhwd 
found. I attach the xorg.0.log file.
[Xorg.0.log.txt](https://github.com/Witko/nvidia-xrun/files/263674/Xorg.0.log.txt)

**Comment by Witko** [comment]
Hi @perbasilopou ,
it seems you have already an X server running. I'm not sure how its with X collisions but it should be definitely possible to have multiple X running on multiple displays(:0,:1 etc).

Maybe try to run "dry run" where you should see the command which nvidia-xrun uses. There you should see the display it wants to use. You can paste the command here for more info.

I would also recommend not to run steam directly - there are some issues with this - i personally use openbox. Its a bit of an overhead but i didnt want to spend too much time investigating whats going on.

**Comment by perbasilopou** [comment]
So i tried:
`nvidia-xrun -d startkde`
nothing happened..It wake up my nvidia card and then turned it off right after the 
`xinit /etx/X11/xinit...` stuff.
(It didn't ask me for a sudo password this time. Maybe that helps somehow)
Do I need to add anything to the dry run command?

**Comment by Witko** [comment]
Hi @perbasilopou ,
what is the state of this?
