### ISSUE TITLE
Steam libGL error

### ISSUE THREAD

**Issue by kaliestrawhat** [Witko/nvidia-xrun#20]
So steam works normally when I start an X session after deleting the runtime libraries, but when I use nvidia-xrun to run a Window Manager and then Steam, Steams throughs out this error `"libGL error: failed to load driver: swrast"`. Any ideas?

**Comment by Witko** [comment]
Hi @kaliestrawhat ,
is this everything it writes? I've had something similar yesterday caused by update of intel drivers - but it wrote it cannot find the i915 first.

Still the swrast means software rendering i believe so thats not good:)
Could you try glxinfo/glxgears within the nvdia-xrun session?

**Comment by kaliestrawhat** [comment]
Hey,
just checked and it also writes `libGL error: No matching fbConfigs or visuals found` just before the `libGL error: failed to load driver: swrast` error, don't know how I missed that.

What should I be looking for with glxinfo/glxgears? 
glxinfo runs and exits successfully and glxgears runs with a lot more fps.

I just realized maybe I shouldn't have opened this issue here since it's more of an issue with steam really, you can close this if you want to..

**Comment by Witko** [comment]
Hi @kaliestrawhat ,
no harm done, I'll gladly help if i can. With glxinfo you should look for the renderer if it runs on dedicated graphics card. Do you also run ```nvidia-xrun steam``` ? I would recommend to go through openbox at least for now - i would like to investigate more about the first option.

**Comment by kaliestrawhat** [comment]
@Witko It does indeed run on the dedicated gpu..
> Do you also run nvidia-xrun steam ?
No, I also go trough a Window manager first.

So I did a clean install again of both nvidia-xrun and steam, installing nvidia-xrun first and also deleting `.steam` and `.local/share/steam`, installed `lib32-nvidia-utils` as a dependency for steam in Arch Linux and apparently it's working..

Once again, sorry for opening this issue here, thank you for your help and thank you for this amazing tool!

**Comment by Witko** [comment]
@kaliestrawhat ,
glad to hear that! Happy gaming;)
