### ISSUE TITLE
Wrong order of nvidia modules unloading

### ISSUE THREAD

**Issue by VadikLeshy** [Witko/nvidia-xrun#22]
Maybe this code:

echo 'Unloading nvidia_drm module'
execute "sudo rmmod nvidia_drm"

echo 'Unloading nvidia_modeset module'
execute "sudo rmmod nvidia_modeset"

echo 'Unloading nvidia module'
execute "sudo rmmod nvidia"

will be better?

**Comment by Witko** [comment]
Hi @VadikLeshy ,
thanks, i've already fixed this. Will be in 0.3 in coming days.
