### ISSUE TITLE
System suspends when NVIDA starting or stoping

### ISSUE THREAD

**Issue by VadikLeshy** [Witko/nvidia-xrun#23]
When xorg starts on NVIDIA system suspends. When xorg closes suspend happens again. 

I replaced

`echo 'Loading nvidia module'`
`execute "sudo modprobe nvidia"`

`echo 'Loading nvidia_drm module'`
`execute "sudo modprobe nvidia_drm"` 
with
`echo 'Loading nvidia module'`
`execute "sudo modprobe nvidia"`

`echo 'Loading nvidia_modeset module'`
`execute "sudo modprobe nvidia_modeset"`

`echo 'Loading nvidia_drm module'`
`execute "sudo modprobe nvidia_drm"`
And now it works just fine.

**Comment by TheCrueltySage** [comment]
Um, the fix for this issue unloads nvidia_modeset on server start (before unloading it again on server stop). Is this really how it's supposed to behave?

**Comment by Witko** [comment]
Thanks @TheCrueltySage ,
had there dummy copy&paste bug:)
