### ISSUE TITLE
X server is running very slow

### ISSUE THREAD

**Issue by alex9099** [Witko/nvidia-xrun#29]
hi, i have a optimis laptop with intel and nvidia 920m, when i start steam everything starts to get slow, is there any way to make this faster?

**Comment by Sudokamikaze** [comment]
Logs?

**Comment by Sudokamikaze** [comment]
I'm running with Archlinux, latest nvidia-dkms on 710m with HD4000 and awesome wm

Games on steam running perfectly!

**Comment by alex9099** [comment]
Where can i check logs?

**Comment by Sudokamikaze** [comment]
@alex9099 What distro you using?

**Comment by alex9099** [comment]
Arch Linux :)

**Comment by Sudokamikaze** [comment]
@alex9099 
/var/log/Xorg.0.log location of Xorg log

**Comment by alex9099** [comment]
i'll check asap, can i start two X instances?

**Comment by Sudokamikaze** [comment]
@alex9099 idk

**Comment by alex9099** [comment]
i'll try and be back with logs

**Comment by alex9099** [comment]
https://ptpb.pw/Ph3n

**Comment by Sudokamikaze** [comment]
@alex9099 What DE/WM u using?

**Comment by alex9099** [comment]
for example, when dragging steamvr window it slowly goes trought the screen, i'm using openbox (tried sddm but it did not work)

**Comment by Sudokamikaze** [comment]
@alex9099 Try to disable compton(if you using) and disable vsync

**Comment by alex9099** [comment]
i think i didnt installed that, how can i disable vsync?

**Comment by alex9099** [comment]
(well, this seems to be a problem, my intel gpu supports vulkan, which is needed for vr games, but steamvr needs a nvidia gpu ...)

**Comment by Sudokamikaze** [comment]
@alex9099 well, idk really, my setup running perfectly 🍰

**Comment by alex9099** [comment]
:/ now it seems to be a little bit faster (restarted nvidia-xrun), anyway, not sure how am i going to solve that vulkan thing...

**Comment by Witko** [comment]
Hi @alex9099 
i had already some games running on my nvidia 980m on vlukan. So there is a possibility that you can run your vr games on nvidia-xrun.
Of course you can run multiple X servers. If im not mistaken the sddm starts in X already. So if you search for the logs you need to know on which display you run(typically :1 as nvidia-xrun starts new X server) So try to search for logs in /var/log/Xorg.1.log.
In general try to run nvidia-settings to check nvidia card is running. Then try to run glxgears or sth similar for crude performance measurements and valuable info. Also glxinfo might come handy.

**Comment by magiruuvelvet** [comment]
I will just drop that here :smile: 

My experience with nvidia-xrun so far is very good. There is a major issue though which is very annoying and I couldn't resolve it yet. I have SDDM on Intel which is my primary X session (KDE Plasma). I prefer to use Intel in most cases. When I need Nvidia i start it on a second X server (:1) on tty2 using nvidia-xrun (i3, to keep it lightweight). Performance is great, no issues. But as soon as i switch away from :1 to :0 (intel) and switch back to :1 opengl seems to "die" and performance drops down to 5\~10 fps and i need to restart the application/game to restore normal performance (60+fps). Vulkan is even worse, it completley dies to black screen and 0\~1fps when switching back to :1, app/game needs restart to restore graphics.

This is a problem for me as I heavily depend on switching between X servers for my daily workflow.

One more thing. VMware Workstation seems to do some kind of blackmagic with OpenGL as performance doesn't drop when switching between X sessions. Really weird. I wonder what VMware does different compared to other apps :thinking:

**Comment by Witko** [comment]
Hi @magiruuvelvet 
glad you like the nvidia-xrun. As for your issues - any clue in logs? Dmesg? I do this kind of switching regularly and do not observe such behaviour. Could be also related to version of drivers.

**Comment by alex9099** [comment]
Well, now i restarted nvidia-xrun with openbox and it seemed to work fine, it seems to have some random behaviour, maybe it is working cause i have intel X11 on tty1?

**Comment by magiruuvelvet** [comment]
@Witko I checked all old and the current logs. On switching it generates a lot of events and device disconnects/re-connects (keyboard, mouse, other...) and plenty of `systemd-logind` messages (got resume, got pause, releasing fd, ...). I have this in both Xorg logs, intel :0 and nvidia :1

I found this interesting. (only in :1)
```
[  7257.931] (II) NVIDIA(0): Setting mode "NULL"
[  7257.932] (II) NVIDIA(0): ACPI: failed to connect to the ACPI event daemon; the daemon
...documentation follows
```
Could it be relevant somehow?

Fresh log files here
dmesg: https://hastebin.com/coqomelotu.hs
Xorg.0.log (intel): https://hastebin.com/jovigipexa.hs
Xorg.1.log (nvidia): https://hastebin.com/rihinazika.scala

**Comment by alex9099** [comment]
not sure if that is relevant :/ i set a simple file for intel and then let nvidia-xrun do the rest :)
This is my X11 intel file

'
Section "Files"
   ModulePath "/usr/lib32/xorg/modules"
   ModulePath "/usr/lib64/xorg/modules"
EndSection

Section "Device"
   Identifier  "Intel Graphics"
   Driver      "intel"
   Option      "AccelMethod" "sna"
   BusID       "PCI:0:2:0"
EndSection
'

**Comment by Witko** [comment]
@magiruuvelvet  - i've had a brief look at the logs. It looks quite clean apart from the ACPI but that should not be an issue.

**Comment by alex9099** [comment]
Now i have startkde working with nvidia-xrun, it now works fine, thanks anyway :)
