### ISSUE TITLE
Unable to unload nvidia_drm

### ISSUE THREAD

**Issue by PhibreOptix** [Witko/nvidia-xrun#32]
Recently an issue has started occurring when closing the X server.
It gets to the point of unloading nvidia_drm which fails as it is in use, then after this every module depends on nvidia_drm fails to unload.

lsmod does not show any dependencies for nvidia_drm

**Comment by Witko** [comment]
Hi @PhibreOptix ,
let me check whether it behaves the same on my machine.

**Comment by Ferouden** [comment]
I have this problem too.
I ran `nvidia-xrun glxgears` and kill it in another tty. 

This is my [logs](http://paste.ubuntu.com/25325034/) ,[Xorg.2.log](http://paste.ubuntu.com/25325056/)

`lsmod | grep nvidia` shows:
```code
nvidia_drm             45056  3
nvidia_modeset        835584  1 nvidia_drm
nvidia              12972032  1 nvidia_modeset
drm_kms_helper        131072  2 i915,nvidia_drm
drm                   299008  29 i915,nvidia_drm,drm_kms_helper
```

And I can remove them only by `rmmod -f`

**Comment by Sowdiyeah** [comment]
I am having the same problem for a while. I can also only remove the module with rmmod -f, but as that completely freezes the computer, I am looking for another solution. Did somebody else find a workaround, or is nobody noticing this?

**Comment by Pro-pra** [comment]
Sowdiyeah, bbswitch work good? 
First step - disable nvidia using bbswitch

**Comment by Sowdiyeah** [comment]
Yeah, if there are no nvidia modules loaded I can disable the secondary card with bbswitch. However, the nvidia_drm module can't be unloaded as the previous guy mentions. This means that bbswitch does nothing.
Even if I modprobe nvidia_drm and then immediately afterwards rmmod nvidia_drm, it already says module in use.
I think the problem started coming after one of the nvidia updates, but I have yet to roll back the driver succesfully to test out.

**Comment by Nightbane112** [comment]
Good news guys, systemd-logind is the culprit here. The current workaround is to run the following command after logging out from the "nvidia-xrun" session
`sudo systemctl stop systemd-logind`

You'll have manually remove the other nvidia modules and switch off the DGPU manually later
    echo 'Unloading nvidia_drm module'
    execute "sudo rmmod nvidia_drm"

    echo 'Unloading nvidia_modeset module'
    execute "sudo rmmod nvidia_modeset"

    echo 'Unloading nvidia module'
    execute "sudo rmmod nvidia"

    echo 'Turning off nvidia GPU'
    execute "sudo tee /proc/acpi/bbswitch <<<OFF"

    echo -n 'Current state of nvidia GPU: '
    execute "cat /proc/acpi/bbswitch"

[Systemd issue on Github](https://github.com/systemd/systemd/issues/6908)
[Reference link from Nvidia Linux Developers portal](https://devtalk.nvidia.com/default/topic/1024407/linux/nvidia_drm-remains-in-use-for-no-apparent-reason-after-xorg-shutdown-/)

**Comment by Sowdiyeah** [comment]
Wow, great news. I have just tested this and confirmed this is the case. I didn't even need to run the code snippet manually. After I ran the `sudo systemctl stop systemd-logind` the machine still ran the code to disable the DGPU automatically (in my case).
