### ISSUE TITLE
Nvidia-XRun uses Gallium OpenGl

### ISSUE THREAD

**Issue by Lightn1ng** [Witko/nvidia-xrun#33]
I'm on Gentoo Linux and using nvidia-xrun causes me to have the Gallium (VMWare) libgl and games won't run.

_Sent from my Samsung SM-G900V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Witko** [comment]
Hi @Lightn1ng ,
why would nvidia-xrun force you to have WMWare libgl? How did you install it?

**Comment by Lightn1ng** [comment]
@Witko 

I installed it correctly via the instructions.

**Comment by Witko** [comment]
@Lightn1ng 
didnt you pick the libgl providing package?

**Comment by Lightn1ng** [comment]
@Witko fixed - needed to apply some Gentoo patches from an overlay to nvidia-xorg.conf

_Sent from my Samsung SM-G900V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Witko** [comment]
@Lightn1ng 
Glad to hear that. If you have better description what was the problem/solution please put it here so it can help others;)
Thanks!

**Comment by Lightn1ng** [comment]
@Witko I just ran the src_prepare part of this ebuild:

https://gpo.zugaina.org/x11-misc/nvidia-xrun

I could have just installed the ebuild, that would have done it too.

_Sent from my Samsung SM-G900V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
