### ISSUE TITLE
Alternative

### ISSUE THREAD

**Issue by 12crowns** [Witko/nvidia-xrun#35]
This script will do the same:

=========================================================
#!/bin/bash
sudo modprobe nvidia_drm
sleep 1
Xorg -config xorg-nv.conf :1 vt8 &
sleep 1
fluxbox -display :1 -rc ~/.fluxbox/init &
DISPLAY=:1 xrdb -load ~/.Xresources

provID=`xrandr -d :1 --listproviders | grep "0x46" | cut -d ' ' -f2 | tr -d ':'`
xrandr -d :1 --setprovideroutputsource $provID 0
xrandr -d :1 --auto
xrandr -d :1 --dpi 96
=======================================================

/etc/X11/xorg-nv.conf
# ================================================ Files

Section "Files"
    ModulePath "/usr/local/lib/nvidia/xorg"
    ModulePath "/usr/local/lib/nvidia/xorg/modules"
EndSection

# ================================================ Module

Section "Module"
	Load		"evdev"
EndSection

# ================================================ Video

Section "Device"
    Identifier	"nvidia"
    Driver	"nvidia"
    BusID	"PCI:1:0:0"
    Option	"UseDisplayDevice"	"none"
EndSection

Section "Device"
    Identifier "intel"
    Driver	"modesetting"
    BusID	"PCI:0:2:0"
EndSection

# ================================================ Screen

Section "Screen"
    Identifier	"nvidia"
    Device	"nvidia"
EndSection

Section "Screen"
    Identifier	"intel"
    Device	"intel"
EndSection

# ================================================ Layout

Section "ServerLayout"
    Identifier	"layout"
    Screen 0	"nvidia"
    Inactive	"intel"
EndSection

# ================================================ Flags

Section "ServerFlags"
	Option 		"BlankTime"		"0"
	Option		"StandbyTime"		"0"
	Option		"SuspendTime"		"0"
	Option		"OffTime"		"0"
EndSection
===============================================================

Furthr reading:
http://us.download.nvidia.com/XFree86/Linux-x86/375.39/README/randr14.html

Only Trusty (xserver-xorg 7.7, xserver-xrorg-core 1.15) worked for me.
nvidia_drv is in /usr/local/lib/nvidia/xorg/modules, 
nvidia openGL libs are in /usr/local/lib/nvidia (must me in LD path, /etc/ld.so.conf.d)
script is run as user. place modprobe in sudoers: no passwd (if needed)
Xorg binary set premissions: 4755
If multiple modesettings providers present choose the correct one. Here 0x46
I am using fluxbox. Choose prefered
xrdb -load or xrdb -merge, both good
If you have multiple screens on :0 and need to use them: start program on :1 like this: DISPLAY=:0 <program>

Reindeer Flotilla

**Comment by Witko** [comment]
Hi @12crowns ,
what is the difference if i may ask? Can't see any obvious one
