### ISSUE TITLE
Problem with openbox

### ISSUE THREAD

**Issue by pablomancera** [Witko/nvidia-xrun#36]
I installed nvidia-xrun following Arch wiki, installing openbox and creating .nvidia-xrun file. After a lot of unsuccessful tries, I tried using gnome-session instead of openbox and it worked.

**Comment by Witko** [comment]
Hi @pablomancera ,
unless you post at least some more info i can hardly help.
Do you have some error output?

**Comment by pablomancera** [comment]
Of course, I didn't realize, sorry.

I get a blank black screen with only the mouse, do you need a log of something?

**Comment by Vosester** [comment]
I am have the same problem with arch and all window mangers, will have logs soon, it's late(for me).
Will bisecting packages to see where the breakage occurred. 
Bumblebee works, I have the issue with Intel too if I don't put the bus id in xorg.conf.
So I think the fault is with Intel.
nvidia-xrun-git 0.3.9.ga56a6a8-1
nvidia 387.12-1
xf86-video-intel-git 1:2.99.917+789+g291fdcdc-1

**Comment by Vosester** [comment]
[Xorg.0.log](https://github.com/Witko/nvidia-xrun/files/1372227/Xorg.0.log)
Here is my xorg log, its a default run of xrun, all modules options disabled, up to date arch.
Modesetting DDX on Intel alone is not working for me, xf86-intel works.

**Comment by pablomancera** [comment]
The problem was with GNOME and Openbox, GNOME can't use alternative windows managers, so I installed lxQT and configured it to use openbox and now everything is working

**Comment by pablomancera** [comment]
Oh, I can use nvidia-xrun directly for running a program through X server, and with openbox for running it with a window manager, now I understand how nvidia-xrun and openbox works, sorry for posting an issue for that xd

**Comment by Vosester** [comment]
Ignore my Issue it's been fixed, it was an xorg-server update, fix in 1.19.5-1 on arch.
You can close this issue now.
