### ISSUE TITLE
No screen found error

### ISSUE THREAD

**Issue by Rafael8661** [Witko/nvidia-xrun#39]
Hi, I am trying to set up nvidia xrun on my notebook with Deepin 15 (ditro based on Debian 8). I put the files in the right directories as the readme file say to do, but when I try to run nvidia-xrun in tty I got a "no screen found" error. I'm sending a pic and the log file as well. Thank you for the help.
[Xorg.1.log](https://github.com/Witko/nvidia-xrun/files/1482430/Xorg.1.log)
[pic.png](https://user-images.githubusercontent.com/17516331/32950184-9a9a56ec-cb8c-11e7-8621-c6445340bb21.png)

**Comment by Pro-pra** [comment]
you need install modesetting xorg driver

**Comment by Rafael8661** [comment]
@Pro-pra I am not sure how should I install it, could you help me? I had made a quick search and it seems to be related to the xserver-xorg-video-intel package, but it already is installed.

**Comment by Pro-pra** [comment]
xserver-xorg-video-modesetting need you

**Comment by Rafael8661** [comment]
@Pro-pra 
```
$ sudo apt install xserver-xorg-video-modesetting
[sudo] password for rafael:
Reading package lists ... Ready
Reading status information ... Ready
Note, a 'xserver-xorg-core' selected 'instead of 'xserver-xorg-video-modesetting '
xserver-xorg-core is already the latest version (2: 1.19.3-2deepin).
```
Should I remove this xserver-xorg-core and download xserver-xorg-video-modesetting deb? I'm afraid of break the xorg.

**Comment by Pro-pra** [comment]
check you /usr/lib/xorg/modules/drivers directory and find modesetting_drv.so
directory path may be differ from my example.
If file modesetting_drv.so present, check path in you /etc/X11/nvidia-xorg.conf section ModulePath

**Comment by Rafael8661** [comment]
The so file is there. That's the nvidia-xorg.conf:
```
Section "Files"
  ModulePath "/usr/lib/nvidia"
  ModulePath "/usr/lib32/nvidia"
  ModulePath "/usr/lib32/nvidia/xorg/modules"
  ModulePath "/usr/lib32/xorg/modules"
  ModulePath "/usr/lib64/nvidia/xorg/modules"
  ModulePath "/usr/lib64/xorg/modules"
EndSection
```
I only put the first section (which have ModulePath).

**Comment by Pro-pra** [comment]
add modulepath string to you section: ModulePath "/usr/lib/xorg/modules"

string add after ModulePath "/usr/lib64/xorg/modules"

**Comment by Rafael8661** [comment]
Same no screen error. :-( 
Do you want log file again?

**Comment by Pro-pra** [comment]
yes

**Comment by Rafael8661** [comment]
[Xorg.1.log](https://github.com/Witko/nvidia-xrun/files/1486250/Xorg.1.log)

**Comment by Pro-pra** [comment]
OK modesetting found, but not found device.

check section Device with identifier "Intel" from you nvidia-xorg.conf

**Comment by Rafael8661** [comment]
```
Section "Device"
  Identifier "intel"
  Driver "modesetting"
  Option "AccelMethod" "none"
EndSection
```

**Comment by Rafael8661** [comment]
@Pro-pra I'm sorry, I just see your edit. Here is the complete file anyway:
```
Section "Files"
  ModulePath "/usr/lib/nvidia"
  ModulePath "/usr/lib32/nvidia"
  ModulePath "/usr/lib32/nvidia/xorg/modules"
  ModulePath "/usr/lib32/xorg/modules"
  ModulePath "/usr/lib64/nvidia/xorg/modules"
  ModulePath "/usr/lib64/xorg/modules"
  ModulePath "/usr/lib/xorg/modules"
EndSection

Section "ServerLayout"
  Identifier "layout"
  Screen 1 "nvidia"
  Inactive "intel"
EndSection

Section "Device"
  Identifier "nvidia"
  Driver "nvidia"
  BusID "PCI:1:0:0"
EndSection

Section "Screen"
  Identifier "nvidia"
  Device "nvidia"
#  Option "AllowEmptyInitialConfiguration" "Yes"
#  Option "UseDisplayDevice" "none"
EndSection

Section "Device"
  Identifier "intel"
  Driver "modesetting"
  Option "AccelMethod" "none"
EndSection

Section "Screen"
  Identifier "intel"  
  Device "intel"
EndSection
```

**Comment by Pro-pra** [comment]
good, check nvidia Device section and BusID parameter.

lspci | egrep 'VGA|3D' 
for real BusID for you intel

**Comment by Rafael8661** [comment]
Ok, here:
```
lspci | egrep 'VGA|3D'
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 5500 (rev 09)
03:00.0 3D controller: NVIDIA Corporation GM108M [GeForce 940M] (rev a2)
```

**Comment by Pro-pra** [comment]
change BusID "PCI:3:0:0"

**Comment by Rafael8661** [comment]
The screen blinked black and I got very excited! But I got sad when it turns to tty again with "nvidia_drm in use" error. T_T Log again.
[Xorg.1.log](https://github.com/Witko/nvidia-xrun/files/1486287/Xorg.1.log)

**Comment by Pro-pra** [comment]
configure nvidia-xrun for lauch application, or lauch manual ex: nvidia-xrun xterm

**Comment by Rafael8661** [comment]
Oh, god, It's working! Thanks, man! Thank you for the patience and help. Thank you so much! :D

**Comment by Pro-pra** [comment]
close issue pleace.

**Comment by Witko** [comment]
@Pro-pra thank you for helping people!

**Comment by RolandVrignon** [comment]
Anyone still on the feed lol ? I exactly have the same issue but don't manage to fix it. 

here is my Xorg.1.log 
[Xorg.1.log](https://github.com/Witko/nvidia-xrun/files/7143178/Xorg.1.log)
 
`lspci | egrep 'VGA|3D'
00:02.0 VGA compatible controller: Intel Corporation TigerLake GT2 [Iris Xe Graphics] (rev 01)
5a:00.0 3D controller: NVIDIA Corporation TU117M (rev ff)
`

And my nvidia.xorg.conf file
 
`Section "Files"
	ModulePath "/usr/lib/nvidia/current"
	ModulePath "/usr/lib/x86_64-linux-gnu/nvidia"
	ModulePath "/usr/lib/x86_64-linux-gnu/nvidia/xorg"
	ModulePath "/usr/lib/x86_64-linux-gnu/nvidia/xorg/modules"
	ModulePath "/usr/lib/xorg"
	ModulePath "/usr/lib/xorg/modules"
EndSection

Section "ServerLayout"
  Identifier "layout"
  Screen 1 "nvidia"
  Inactive "intel"
EndSection

Section "Device"
  Identifier "nvidia"
  Driver "nvidia"
  BusID "PCI:5a:0:0"
EndSection

Section "Screen"
  Identifier "nvidia"
  Device "nvidia"
  Option "AllowEmptyInitialConfiguration" "Yes"
  Option "UseDisplayDevice" "none"
EndSection

Section "Device"
  Identifier "intel"
  Driver "modesetting"
  Option "AccelMethod" "none"
EndSection

Section "Screen"
  Identifier "intel"  
  Device "intel"
EndSection`

If anyone have an idea
@Pro-pra 
@Witko

**Comment by dalloc** [comment]
> Anyone still on the feed lol ? I exactly have the same issue but don't manage to fix it.
> 
> here is my Xorg.1.log [Xorg.1.log](https://github.com/Witko/nvidia-xrun/files/7143178/Xorg.1.log)
> 
> `lspci | egrep 'VGA|3D' 00:02.0 VGA compatible controller: Intel Corporation TigerLake GT2 [Iris Xe Graphics] (rev 01) 5a:00.0 3D controller: NVIDIA Corporation TU117M (rev ff) `
> 
> And my nvidia.xorg.conf file
> 
> `Section "Files" ModulePath "/usr/lib/nvidia/current" ModulePath "/usr/lib/x86_64-linux-gnu/nvidia" ModulePath "/usr/lib/x86_64-linux-gnu/nvidia/xorg" ModulePath "/usr/lib/x86_64-linux-gnu/nvidia/xorg/modules" ModulePath "/usr/lib/xorg" ModulePath "/usr/lib/xorg/modules" EndSection
> 
> Section "ServerLayout" Identifier "layout" Screen 1 "nvidia" Inactive "intel" EndSection
> 
> Section "Device" Identifier "nvidia" Driver "nvidia" BusID "PCI:5a:0:0" EndSection
> 
> Section "Screen" Identifier "nvidia" Device "nvidia" Option "AllowEmptyInitialConfiguration" "Yes" Option "UseDisplayDevice" "none" EndSection
> 
> Section "Device" Identifier "intel" Driver "modesetting" Option "AccelMethod" "none" EndSection
> 
> Section "Screen" Identifier "intel" Device "intel" EndSection`
> 
> If anyone have an idea @Pro-pra @Witko

I figured that numbers in BusID should be in decimal format. lspci output is in hex format, so you just need to convert lspci output back to decimal format. In your case, BusID should be "PCI:90:0:0"
