### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by skoehler** [Witko/nvidia-xrun#43]
All I get is a black screen. I'm using nvidia drivers 387.34 and xorg-server 1.19.5 on Gentoo (kernel 4.14.3).
I uninstalled bumblebee, primus, and virtualgl just to be sure. Of course I rebootet before I tried nvidia-xrun.

How can I debug this? The Xorg log file is clean, no errors or warnings. Still the screen remains black.

**Comment by Witko** [comment]
What exactly did you run?

**Comment by skoehler** [comment]
I tried `nvidia-xrun mate-terminal` and `nvidia-xrun openbox-session`

**Comment by Witko** [comment]
Are you sure you looked into the right Xorg log file? It depends on the display nvidia-xrun initializes. Usually it is /var/log/Xorg.1.log

**Comment by skoehler** [comment]
I'm sorry. I made some progress. The nvidia-drm module was missing and thus the I got the blank screen. Once the nvidia-drm module was loaded correctly, things started working. I cannot start steam, but that's a different issue.

One issue remains: once the nvidia-drm module is loaded, it cannot be unloaded anymore. I tried "rmmod -f" to force an upload, but I got some kernel oops afterwards.

**Comment by wallefan** [comment]
I'm also having this issue, and I'm pretty sure nvidia-drm is getting loaded properly.  I tried Ctrl+C'ing nvidia-xrun after it had turned the GPU on, manually running `modprobe nvidia-drm` and/or `sudo nvidia-modprobe` (both of which completed without issue), and running nvidia-xrun again, but that didn't help.  I'm unsure what else to try.  This is the first Google hit for "nvidia-xrun black screen" and the only one that looks even remotely relevant.  I hate to reopen an old thread but I'm not sure where else to post this.

Setup: Arch Linux, AMD 6900HX with integrated graphics, RTX 3070Ti, Linux 5.18.13-arch1-1, Nvidia proprietary drivers v515.57-7

**Comment by wallefan** [comment]
UDPATE: I've resolved this issue by doing a search and replace in /etc/X11/nvidia-xorg.conf of intel with amd, so that X11 ignores the correct graphics adapter in Nvidia mode.  The NVidia display output is only visible from the HDMI output (the built in display remains dark, because nvidia-xrun didn't switch it to the Nvidia card's eDP output) but that's a separate issue.
