### ISSUE TITLE
README.md fix

### ISSUE THREAD

**Issue by slump64** [Witko/nvidia-xrun#50]
it is `~./Xresources` in README thou, it is supposed to be `~/.Xresources` or even `~/.Xdefaults`, am I right? Bit confusing.

**Comment by Witko** [comment]
@slump64 ,
yes you are right, thanks for noticing!

**Comment by slump64** [comment]
Also this command ain't right!
lspci | grep -i nvidia | awk '{print $1}`
It's ' at the start and ` an the end lol

**Comment by slump64** [comment]
See what it does with md formatting? :D

**Comment by slump64** [comment]
Also there's no Install paragraph, so if I use something besides Arch, Suse and some others, like Void for example, I just don't know how to install this script. Tho it's just a script so I guess it can be install with some bash commands? Maybe create install.sh script?

**Comment by Witko** [comment]
@slump64 ,
i will try to cover this somehow:)

**Comment by Witko** [comment]
@slump64 As for the install - making the package is quite distro specific. Also the install paths. In theory there could be parametrized install script but that would not add too much. If you check the PKGBUILD for AUR you should know everything about install.
