### ISSUE TITLE
Can't run Vulkan

### ISSUE THREAD

**Issue by burningserenity** [Witko/nvidia-xrun#54]
I finally got nvidia-xrun to work by using fluxbox instead of openbox. The problem is that Vulkan still doesn't work. If I run vulkaninfo, the output states that it cannot create a Vulkan device. I tried this with both the hybrid graphics drivers and the NVIDIA only drivers. I'm using Manjaro.

**Comment by burningserenity** [comment]
When I run `glxinfo | grep Vulkan` I get an error about primus failing to acquire modesetting permission.

**Comment by ArchangeGabriel** [comment]
Generally it’s part of a package called `vulkan-validation-layers`. At least the case for @burningserenity.

**Comment by burningserenity** [comment]
Per the Arch wiki: https://wiki.archlinux.org/index.php/Vulkan
I removed the package vulkan-intel and added this line to my .zshrc (.bashrc or .bash_profile if you're not using ZSH):
` export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json`
Vulkan now works as expected. Perhaps add the wiki page to troubleshooting?
