### ISSUE TITLE
nvidia driver

### ISSUE THREAD

**Issue by NikSudo** [Witko/nvidia-xrun#55]
Hello, I'm trying to install a Tomahawk app, I do not see any mentions of the NVIDIA drivers in the build. However, an error occurs (missing 'nvidia' dependency for 'nvidia-xrun').
I am an arch user, the NVIDIA-390xx and nvidia-xrun drivers are installed, respectively. Your package works, it does not swear at startup

**Comment by Witko** [comment]
Hi @NikSudo ,
the problem is that none of the nvidia driver packages has provides set. So i cannot state a higher level requirement for some nvidia driver. So at this stage it requires "nvidia" package. For you the solution could be to manually edit the PKGBUILD and replace the dependency.
