### ISSUE TITLE
Wrong resolution

### ISSUE THREAD

**Issue by DrUlysses** [Witko/nvidia-xrun#56]
Hi, I'm running nvidia-390 on GT540M and my laptop has 1920x1080 resolution, but the maximum for CRT-0 is 1600x900 But the PRIME one shows the right resolution. I do have i3wm if this is important

**Comment by Witko** [comment]
Hi @DrUlysses ,
its a bit weird - i had a different problem - i didnt have FullHD resolution only 4K, so i have this in the config _/etc/X11/nvidia-xorg.conf.d/10-monitor.conf_:
```
Section "Monitor"
    Identifier "eDP-1-1"
    # 1920x1080 59.96 Hz (CVT 2.07M9) hsync: 67.16 kHz; pclk: 173.00 MHz
    Modeline "1920x1080_60.00"  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync
EndSection

Section "Screen"
    Identifier "Screen0"
    Monitor "eDP-1-1"
    DefaultDepth 24
    SubSection "Display"
        Modes "1920x1080_60"
    EndSubSection
EndSection

Section "Device"
    Identifier "Device0"
    Driver "nvidia"
EndSection
```

So that could help you. Not sure how to fix this in general - maybe browse Nvidia archlinux pages.

**Comment by DrUlysses** [comment]
Thanks for the answer! But my /etc/X11/nvidia-xorg.conf.d folder is just empty, mb is some way to generate that conf file?

**Comment by Witko** [comment]
Yes, by hand:) i had to write it myself. In theory you should be able to also remove the modes. But check the nvidia generic page for more info

**Comment by DrUlysses** [comment]
I think this is not because of screen. I wrote the config, but it does not help at all. So I just tried to disable this strange CRT-0 and the resolution become normal. Only i3 is somewhy small. (In startx it looks normal, but I can't use nvidia-settings in startx) 
![123123](https://user-images.githubusercontent.com/8532343/40487090-69e0f8ba-5f63-11e8-8ccd-b594ddffc531.png)

![image](https://user-images.githubusercontent.com/8532343/40487159-9103a64a-5f63-11e8-8aad-869bda8d67cc.png)

**Comment by Witko** [comment]
@DrUlysses where did you start the nvidia-xsettings? It should be working if you are in openbox session with nvidia-xrun.

**Comment by DrUlysses** [comment]
So I have reinstalled all the nvidia things (bumblebee, drivers, etc) and I'm using optirun to launch now.
I don't want to install the nvidia-xrun now, because I don't want to have some problems with card now, so I will close the thread for now.
