### ISSUE TITLE
Some keyboard bindings does not work in some games

### ISSUE THREAD

**Issue by andennn** [Witko/nvidia-xrun#6]
Games tested:
* **CS:GO (steam)**  All keys work.
* **Cities Skyline (steam)** Only mouse. No keyboard commands work.
* **Minecraft** Some keyboard buttons work but can't press mouse button to start new game and/or press ESC key to return to game. Other menu buttons like options etc does work.
* **Stonehearth (wine/steam)** Only mouse. No keyboard commands work.

**Comment by Witko** [comment]
Hi Andennn,
its a bit weird, there is nothing regarding keyboard in nvidia-xrun. As for the games I played Cities: Skylines via nvidia-xrun->openbox->steam just fine. I never had issues with keyboard nor mouse as far as I can remember. I recommend checking Xorg.0.log and dmesg too, there might be some clues.

**Comment by andennn** [comment]
I ran it in openbox instead of from the tty as you said and the problem seem to be gone.

**Comment by andreas-center** [comment]
Could you check if there is a solution to this as openbox doesen't work either?
