### ISSUE TITLE
nvidia_uvm needs unload

### ISSUE THREAD

**Issue by tkkcc** [Witko/nvidia-xrun#62]
archlinux 4.17.3-1, with `nvidia` and `opencl-nvidia` installed

I found `nvidia_uvm` needs unload too, otherwise `rmmod nvidia` will fail

```diff

echo 'Unloading nvidia_drm module'
execute "sudo rmmod nvidia_drm"

echo 'Unloading nvidia_modeset module'
execute "sudo rmmod nvidia_modeset"

+ echo 'Unloading nvidia_uvm module'
+ execute "sudo rmmod nvidia_uvm"

echo 'Unloading nvidia module'
execute "sudo rmmod nvidia"
```

**Comment by andrebrait** [comment]
I can confirm that. I also had to unload it for the PRIME Indicator Plus.

**Comment by andrebrait** [comment]
I submitted a PR for this but that's already fixed in @Fincer fork

**Comment by Fincer** [comment]
Yes, it's a very trivial fix. ^
