### ISSUE TITLE
Xorg falling back to software renderer on Fedora 28

### ISSUE THREAD

**Issue by BlackDragonDv** [Witko/nvidia-xrun#65]
Hello everyone. I'm using nvidia-xrun on my Arch and it's works perfectly. I want to use it too on Fedora 28 and it's not working. I have Nvidia drivers installed from negativo17 repo, and bbswitch (just this without bumblebee) from chenxiaolong/bumblebee copr repository. I've blacklisted nouveau and nvidia modules too. When I'm trying to use nvidia-xrun it works, but uses software renderer (glxinfo gives llvmpipe OpenGL provider) instead of Nvidia driver. In Xorg log there is:
> [   245.487] (EE) NVIDIA(0): Failed to initialize the GLX module; please check in your X
[   245.487] (EE) NVIDIA(0):     log file that the GLX module has been loaded in your X
[   245.487] (EE) NVIDIA(0):     server, and that the module is the NVIDIA GLX module.  If
[   245.487] (EE) NVIDIA(0):     you continue to encounter problems, Please try
[   245.487] (EE) NVIDIA(0):     reinstalling the NVIDIA driver.

It seems Xorg fails to load GLX module for Nvidia. When I continue searching log I can find:
> [   245.381] (II) LoadModule: "glx"
[   245.390] (II) Loading /usr/lib64/xorg/modules/extensions/libglx.so
[   245.394] (II) Module glx: vendor="X.Org Foundation"
[   245.394] 	compiled for 1.19.6, module version = 1.0.0
[   245.394] 	ABI class: X.Org Server Extension, version 10.0

Xorg definitely loading wrong GLX module. It should load libglx.so from /usr/lib64/nvidia/xorg instead of /usr/lib64/xorg/modules/extensions. On my Arch Xorg loads correct module. In theory I can make Nvidia libglx.so symlink to /usr/lib64/xorg/modules/extensions, but this can break running Xorg on Intel card (I don't want to use Nvidia whole time, only when I need it). I think it can be wrong configuration, but I have no idea how to fix it. I've tried to remove paths to Xorg modules and keep only Nvidia, but then Xorg fails completely - It can't find GLX module and crashes with "No screens found" error. Any ideas?

**Comment by BlackDragonDv** [comment]
Here is whole Xorg log if you need it
[Xorg.1.log](https://github.com/Witko/nvidia-xrun/files/2237946/Xorg.1.log)

**Comment by Witko** [comment]
Hi @BlackDragonDv ,
The problem is that the path is hardcoded in the script. So editing this would help i believe. But this script is mainly focused on ArchLinux. Maybe with a bigger overhaul i'll add support for multiple distros

**Comment by BlackDragonDv** [comment]
@Witko Yeah, I can see this now. On Fedora Nvidia GLX module is located in (for 64bit OS) /usr/lib64/nvidia/xorg instead of /usr/lib64/nvidia/xorg/modules like in Arch Linux. Adding this path to nvidia-xorg.conf makes nvidia-xrun works without problems on Fedora (OpenGL, Vulkan etc. works like a charm). Thank you for answer.
