### ISSUE TITLE
XDG Specification support

### ISSUE THREAD

**Issue by mfr-itr** [Witko/nvidia-xrun#72]
Did you consider supporting the XDG specification for config files? The values in https://github.com/Witko/nvidia-xrun/blob/master/nvidia-xinitrc would then be:
```bash
CONFIG_DIR=${XDG_CONFIG_HOME:-$HOME/.config}/xorg

$CONFIG_DIR/Xresources
$CONFIG_DIR/Xmodmap
$CONFIG_DIR/nvidia-xinitrc
```
A fallback to the current values could be kept for compatibility.
I can do a PR if you would merge it.

**Comment by Witko** [comment]
Hi @mfr-itr ,
seems like a good approach to me. I'd be happy if you can create the PR.
Thanks!
