### ISSUE TITLE
Screen Tearing

### ISSUE THREAD

**Issue by TriaSirax** [Witko/nvidia-xrun#75]
I managed to get the script work. But in nvidia xorg session i'm experiecing screen tearing. What should i do to prevent that?

**Comment by X1aomu** [comment]
You can refer to https://wiki.archlinux.org/index.php/NVIDIA/Troubleshooting#Avoid_screen_tearing

**Comment by TriaSirax** [comment]
It is not working on laptops it requires an external screen. However i found a workaround. In /bin/nvidia-xrun I'm loading nvidia-drm module with 'modeset=1' parameter. That fixes fps to screen's fresh rate. (60 in my case) and this prevents tearing.

**Comment by TriaSirax** [comment]
@eizanprime If I remember correctly it was crashing when i back to intel session. But I'm using same tty now. I just log out from intel session and type nvidia-xrun in the same tty. I don't use a display manager.

I added parameter to /bin/nvidia-xrun script file.
Under Loading Modules section, this line:

echo 'Loading nvidia_drm module'
execute "sudo modprobe nvidia_drm"

now looks like this:

echo 'Loading nvidia_drm module'
execute "sudo modprobe nvidia_drm modeset=1"

You can also add this as a kernel parameter. To do this, type:

sudo nano /etc/default/grub

Find this line:
GRUB_CMDLINE_LINUX_DEFAULT=" "

and add this parameter inside the quotes.
nvidia-drm.modeset=1
 Probably there will be other parameters,too. Separate parameters with a space.

**Comment by Witko** [comment]
I will try to think about a way how to add such params in config file or sth

**Comment by Witko** [comment]
There is support for config file in next release(in few days). There you can specify the modules to load and also params.
