### ISSUE TITLE
Install for ubuntu

### ISSUE THREAD

**Issue by iNyamuk** [Witko/nvidia-xrun#81]
Can you tell me how to install this on ubuntu?
or this is only for Arch?

**Comment by anar4732** [comment]
Copy this files to your system:

- /usr/bin/nvidia-xrun
- /etc/X11/nvidia-xorg.conf
- /etc/X11/xinit/nvidia-xinitrc

Create folders:

- /etc/X11/xinit/nvidia-xinitrc.d (Empty Folder)
- /etc/X11/nvidia-xorg.conf.d (Empty Folder)

Done. :)

**Comment by blazessdd** [comment]
make sure the library path are correct  i had to change /lib64/ with /lib/ in the configuration file ( to be honest have added more paths without deleting the existent)
