### ISSUE TITLE
Screen 0 deleted because of no matching config section

### ISSUE THREAD

**Issue by gmorenz** [Witko/nvidia-xrun#89]
I'm trying to set this up on a fresh install of arch on a new laptop. Apart from debugging the install process so far has looked like: Install `nvidia-xrun` aur package, and change the `BusID` to match `lspci` (3b:0:0). `nvidia-xrun` fails with `(EE) no screends found(EE)`.

The obviously relevant part of the Xorg.0.log is this:

```
[    17.831] (EE) Screen 0 deleted because of no matching config section.
[    17.831] (II) UnloadModule: "modesetting"
[    17.831] (EE) Device(s) detected, but none match those in the config file.
[    17.831] (EE) 
Fatal server error:
[    17.831] (EE) no screens found(EE) 
```

[Full Xorg.0.log](https://gist.github.com/gmorenz/63e47a1a25b4a238d2ac989fbbc2045c), [lspci output](https://gist.github.com/gmorenz/a86b37aa02e98c6a7e567b5440c6cfb9) (nvidia is the second last line), [/etc/X11/nvidia-xorg.conf](https://gist.github.com/gmorenz/3573141199ae1616a88d9dc7e8a808f5), [xrun output](https://gist.github.com/gmorenz/730bc6e2701ab438b98c0fb1428be667) (`nvidia-xrun 2>&1 1>xrun-out`).

Any ideas?

**Comment by rollofant** [comment]
Same issue here with antergos on an old macbook air (3.2/Geforce 320m). Tried with nouveau and nvidia340 drivers, gdm and lightdm, gnome 3 and mate. Im (re-)installing in different ways since 5 days - or nights ;-) with no success-

**Comment by Witko** [comment]
Hi Guys,
i had similar problem today when testing new version, then it worked. So give it a try in few days.

**Comment by WhyNotHugo** [comment]
I'm having pretty much the same issue. Also updated the BusID.
Full X log [here](https://gist.github.com/WhyNotHugo/403c39d05116fc9b3a369662a4c839c1).

**Comment by WhyNotHugo** [comment]
I managed to figure out what failed for me. `BusID` is supposed to be in decimal, while `lspci` lists them in hex. So you need to convert them.

I'll use my case as an example:

```
$ lspci | grep VGA   
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (Whiskey Lake)
3c:00.0 VGA compatible controller: NVIDIA Corporation TU106 [GeForce RTX 2070] (rev a1)
$ grep BusID /etc/X11/nvidia-xorg.conf
BusID "PCI:60:0:0"
```

I hope this helps some of you. Note that if your nvidia card is external, you'll also need to add `Option "AllowExternalGpus" "True"` to the screen section of your `xorg.conf`.

**Comment by ingmarcosp** [comment]
the same problem here with opensuse leap 15.1

**Comment by WhyNotHugo** [comment]
@ingmarcosp Does the above solution not work for you?
