### ISSUE TITLE
All windows stuck in left upper corner

### ISSUE THREAD

**Issue by tskaar** [Witko/nvidia-xrun#9]
Hi!
I had an issue where all the windows appeared stuck in the upper left corner of the screen, but if this isn't an issue for all maybe you can put this quick fix as "uncomment if needed" line.

Proposed fix:
`#Option "nvidiaXineramaInfo"	"False"  # Uncomment if the windows stuck in upper left corner` 
I put it in your proposed file (from the AUR): `nvidia.xorg.conf.d/10-nvidia-empty.conf`

**Comment by andreas-center** [comment]
I can confirm that this solved the problem for me too.

**Comment by Witko** [comment]
Great guys, thank you very much. I'm not sure whether this is a temporal fix or it has to be like this from now on. I will try this out too and we'll see.

**Comment by andreas-center** [comment]
This is how i solved it:

    /etc/X11/nvidia-xorg.conf

    [...]
    Section "Screen"
        Identifier "nvidia"
        Device "nvidia"
        #  Option "AllowEmptyInitialConfiguration" "Yes"
        #  Option "UseDisplayDevice" "none"
       Option "nvidiaXineramaInfo" "False" # Uncomment if the windows stuck in upper left corner
    EndSection
    [...]

**Comment by sjseventyeight** [comment]
Thank you so much... Been trying to fix this for days!
