### ISSUE TITLE
Merge with nvidia-xrun-pm

### ISSUE THREAD

**Issue by michelesr** [Witko/nvidia-xrun#94]
Hello @Witko, I would like to thank you for your brilliant project. I've been working on a [fork](https://github.com/michelesr/nvidia-xrun-pm) that basically removed bbswitch and added a systemd service for automatically shutdown the NVIDIA card at boot. I've seen now that you somehow removed bbswitch by using a similar approach so maybe it makes sense to have a look if my fork could be merged again into the main project.

Let me know your thoughts.

**Comment by michelesr** [comment]
@Witko: any update on this?

**Comment by Witko** [comment]
Hi @michelesr ,
thanks for your work. I had laptop issues(my Alienware R1 burned out) and it took some time to get a replacement. Now I'm a bit struggling with the new one - it has ACPI issues. So right now im still unable to test it. But i've merged the pull request as the change is obvious:)
Thanks again!!
